### ISSUE TITLE
Is it possible to have date presets like AirBnb?

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [zigomir/nanocal#18]
I need to have the date presets. Is this possible with nanocal?

http://airbnb.io/react-dates/?selectedKind=PresetDateRangePicker&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by zigomir** [comment]
Not at the moment, but it should be possible to add this. Maybe even with ease. Feel free to open PR, I'd happily include anything that's useful addition like this one.
